[package]
name = "generalized_suffix_array"
version = "0.1.0"
authors = ["mossadnik <ossadnik.matthias.gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]
